name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push event but only for the main branch
  #push:
  #  branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: main
    
      # Checks-out JFFT a needed depenancy
      - name: Checkout FFT repo
        uses: actions/checkout@v2
        with:
          repository: jontio/JFFT
          path: JFFT
          
      # Checks-out libopusenc a needed depenancy
      - name: Checkout libopusenc repo
        uses: actions/checkout@v2
        with:
          repository: xiph/libopusenc
          path: libopusenc

      # Setup apt dependencies using the runners shell
      - name: Setup apt dependencies
        run: |
          sudo apt-get install qt5-default cpputest build-essential qtmultimedia5-dev automake libtool libopus-dev libogg-dev libqt5multimedia5-plugins
          
      # build and install libopusenc
      - name: Buils and install libopusenc
        run: |
          cd libopusenc
          ./autogen.sh
          ./configure
          make
          sudo make install
          sudo ldconfig
          echo finished installing libopusenc.
          
      # Run unit tests
      - name: Run unit tests
        run: |
          cd main
          qmake CONFIG+=CI
          make
          ./jsquelch -v
          echo finished testing.
          
      # Build application
      - name: Build application
        run: |
          cd main
          make clean
          qmake CONFIG-=CI
          make
          echo finished build.
          
      # upload artifact    
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build.zip
          path: |
            main/jsquelch
