name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push event but only for the main branch
  #push:
  #  branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: jsquelch
    
      # Checks-out JFFT a needed depenancy
      - name: Checkout FFT repo
        uses: actions/checkout@v2
        with:
          repository: jontio/JFFT
          path: JFFT
          
      # Checks-out libopusenc a needed depenancy
      - name: Checkout libopusenc repo
        uses: actions/checkout@v2
        with:
          repository: xiph/libopusenc
          path: libopusenc

      # Setup apt dependencies using the runners shell
      - name: Setup apt dependencies
        run: |
          sudo apt-get install qt5-default cpputest build-essential qtmultimedia5-dev automake libtool libopus-dev libogg-dev libqt5multimedia5-plugins checkinstall -y
          
      # build package and install libopusenc-dev
      - name: Build package and install libopusenc-dev
        run: |
          cd libopusenc
          ./autogen.sh
          ./configure
          make
          sudo checkinstall \
            --pkgsource="https://github.com/xiph/libopusenc" \
            --pkglicense="BSD" \
            --maintainer="jontio@i4free.co.nz" \
            --pkgversion="0.2.1-8-g427d611" \
            --pkgrelease="1" \
            --pkgname=libopusenc-dev \
            --provides=libopusenc-dev \
            --summary="Library for encoding .opus audio files and live streams." \
            --requires="libopus-dev \(\>=1.3\), libogg-dev \(\>=1.3\)" \
            -y
          sudo ldconfig
          echo finished installing libopusenc-dev.
          
      # Run unit tests
      - name: Run unit tests
        run: |
          cd jsquelch
          qmake CONFIG+=CI
          make
          ./jsquelch -v
          echo finished testing.
          
      # Build application
      - name: Build application
        run: |
          cd jsquelch
          qmake CONFIG-=CI
          make
          echo finished build.
    
      # Package application
      - name: Package application for DEB
        run: |
          cd jsquelch
          mkdir jsquelch_1.0-1
          mkdir -p jsquelch_1.0-1/usr/local/bin
          cp jsquelch jsquelch_1.0-1/usr/local/bin
          mkdir -p jsquelch_1.0-1/DEBIAN
          cp control jsquelch_1.0-1/DEBIAN
          dpkg-deb --build jsquelch_1.0-1
          echo '#!/bin/bash' > install.sh
          echo 'sudo apt install ./jsquelch_1.0-1.deb ../libopusenc/libopusenc-dev_0.2.1-8-g427d611-1_amd64.deb' >> install.sh
          echo '#!/bin/bash' > uninstall.sh
          echo 'sudo apt remove jsquelch libopusenc-dev' >> uninstall.sh
          sudo chmod +x install.sh
          sudo chmod +x uninstall.sh
          
      # upload artifact    
      - name: Upload DEB packages
        uses: actions/upload-artifact@v2
        with:
          name: jsquelch_deb_packages
          path: |
            jsquelch/install.sh
            jsquelch/uninstall.sh
            jsquelch/jsquelch_1.0-1.deb
            libopusenc/libopusenc-dev_0.2.1-8-g427d611-1_amd64.deb
